version: "3"
services: 
  web:
    build: .
    environment: 
      - NODE_ENV=development
      - MYSQL_ADDR=mysql://root:example@db:3306/sails
    ports:
      - 1337:1337
    command: npm run dev
    volumes: 
      - ./:/app 
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=sails
      - MYSQL_USER=sailsUser
      - MYSQL_PASSWORD=sailsPassword
    volumes:
    - ./_docker/mysql:/var/lib/mysql